name: PR Bouncer

on:
  pull_request:
    types: [opened, edited, reopened, synchronize] # Trigger on various pull request events

jobs:
  check-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Use a recent version
      - name: Check for external changes
        run: |
          # Set the allowed directory
          ALLOWED_DIR="uvasds-services/templates/ds2002"
          # Get the list of changed files
          CHANGED_FILES=$(git diff --name-only --relative HEAD^ HEAD)
          # Check if any of the changed files are outside the allowed directory
          if [[ $(echo "$CHANGED_FILES" | grep -q "^$ALLOWED_DIR/") ]] ; then
            # No changes outside the allowed directory
            echo "All changes within allowed directory"
            exit 0
          else
            # Changes outside the allowed directory
            echo "Changes outside the allowed directory detected"
            echo "Pull request rejected."
            exit 1
          fi
